# Generated by Django 4.2.7 on 2023-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authApi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_object",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("pod", "Pod")],
                default="other",
                max_length=10,
            ),
        ),
    ]
