# Generated by Django 4.2.7 on 2023-11-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApi', '0004_feedback'),
        ('authApi', '0002_remove_customuser_user_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feedbacks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApi.feedback'),
        ),
    ]
