# Generated by Django 4.2.7 on 2023-11-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApi', '0004_feedback'),
        ('authApi', '0003_student_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feedbacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApi.feedback'),
        ),
    ]
