# Generated by Django 4.2.7 on 2023-11-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("scid", models.AutoField(primary_key=True, serialize=False)),
                ("course_code", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=255)),
                ("term", models.CharField(max_length=20)),
                ("course_type", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("active", models.BooleanField()),
                ("comment", models.TextField()),
                ("feedback", models.JSONField()),
            ],
        ),
    ]
