# Generated by Django 4.2.7 on 2023-11-16 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("foundation", "Foundation"),
                            ("diploma", "Diploma"),
                            ("bsc", "Bsc"),
                            ("bs", "Bs"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Rating should be atleast 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message="Rating should be atmost 5"
                            ),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=150)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseApi.course",
                    ),
                ),
            ],
            options={
                "unique_together": {("course",)},
            },
        ),
    ]
