# Generated by Django 4.2.7 on 2023-11-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authApi", "0001_initial"),
        ("courseApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="student",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="authApi.student",
            ),
            preserve_default=False,
        ),
    ]
