# Generated by Django 4.2.7 on 2023-11-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApi', '0002_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='feedback',
        ),
    ]
