# Generated by Django 4.2.7 on 2023-11-16 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApi', '0003_remove_course_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating should be atleast 1'), django.core.validators.MaxValueValidator(5, message='Rating should be atmost 5')])),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApi.course')),
            ],
        ),
    ]
