# Generated by Django 4.2.7 on 2023-11-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0006_remove_student_feedbacks'),
        ('courseApi', '0005_feedback_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApi.student'),
        ),
    ]
