# Generated by Django 4.2.7 on 2023-11-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0006_remove_student_feedbacks'),
        ('courseApi', '0006_alter_feedback_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('student', 'course')},
        ),
    ]
